class Constants:
    SEASON_RECORD = "season_record"
    TEAMS_INFO = "teams_info"
    TEAMS_ROSTER = "teams_roster"
    PLAYERS_INFO = "players_info"
    TEAM_STATS = "team_stats"
    PLAYER_STATS = "player_stats"
    TEAM_MATCHUPS = "team_matchups"
    PLAYER_AWARDS = "player_awards"
    GAME_SCHEDULE = "game_schedule"
    ADVANCED_PLAYER_SEASON_STATS = "advanced_player_season_stats"
    ADVANCED_TEAM_SEASON_STATS = "advanced_team_season_stats"
