# Generated by Django 4.2.25 on 2025-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_teamstats_season_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMatchups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=10)),
                ('team_id', models.IntegerField()),
                ('team_abbreviation', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=50)),
                ('game_id', models.CharField(max_length=20)),
                ('game_date', models.DateField()),
                ('matchup', models.CharField(max_length=50)),
                ('wl', models.CharField(max_length=2)),
                ('min', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg_pct', models.FloatField()),
                ('fg3m', models.IntegerField()),
                ('fg3a', models.IntegerField()),
                ('fg3_pct', models.FloatField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft_pct', models.FloatField()),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('plus_minus', models.FloatField()),
                ('opponent_team_id', models.IntegerField()),
                ('pts_cumsum', models.IntegerField()),
                ('fgm_cumsum', models.IntegerField()),
                ('fga_cumsum', models.IntegerField()),
                ('fg_pct_cumsum', models.FloatField()),
                ('fg3m_cumsum', models.IntegerField()),
                ('fg3a_cumsum', models.IntegerField()),
                ('fg3_pct_cumsum', models.FloatField()),
                ('ftm_cumsum', models.IntegerField()),
                ('fta_cumsum', models.IntegerField()),
                ('ft_pct_cumsum', models.FloatField()),
                ('oreb_cumsum', models.IntegerField()),
                ('dreb_cumsum', models.IntegerField()),
                ('reb_cumsum', models.IntegerField()),
                ('ast_cumsum', models.IntegerField()),
                ('stl_cumsum', models.IntegerField()),
                ('blk_cumsum', models.IntegerField()),
                ('tov_cumsum', models.IntegerField()),
                ('pf_cumsum', models.IntegerField()),
                ('plus_minus_cumsum', models.FloatField()),
                ('win', models.IntegerField()),
                ('win_cum', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('loss_cum', models.IntegerField()),
            ],
        ),
    ]
