# Generated by Django 4.2.25 on 2025-10-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teammatchups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammatchups',
            name='ast_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='blk_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='dreb_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='fg3_pct_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='fg3a_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='fg3m_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='fg_pct_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='fga_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='fgm_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='ft_pct_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='fta_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='ftm_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='loss_cum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='opponent_team_id',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='oreb_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='pf_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='plus_minus_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='pts_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='reb_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='stl_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='tov_cumsum',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='win',
        ),
        migrations.RemoveField(
            model_name='teammatchups',
            name='win_cum',
        ),
    ]
