# Generated by Django 4.2.30 on 2026-06-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_date_playerstats_game_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playerinfo',
            table='players_info',
        ),
        migrations.AlterModelTable(
            name='playerstats',
            table='player_stats',
        ),
        migrations.AlterModelTable(
            name='seasonrecord',
            table='season_record',
        ),
        migrations.AlterModelTable(
            name='teaminfo',
            table='teams_info',
        ),
        migrations.AlterModelTable(
            name='teammatchups',
            table='team_matchups',
        ),
        migrations.AlterModelTable(
            name='teamroster',
            table='teams_roster',
        ),
        migrations.AlterModelTable(
            name='teamstats',
            table='team_stats',
        ),
    ]
