# Generated by Django 4.2.30 on 2026-07-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_playerawards_textfields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playerawards',
            constraint=models.UniqueConstraint(fields=('player_id', 'season', 'description', 'all_nba_team_number', 'month', 'week'), name='player_awards_unique_player_season_desc_month_week'),
        ),
        migrations.AddConstraint(
            model_name='playerinfo',
            constraint=models.UniqueConstraint(fields=('season_id', 'full_name'), name='players_info_unique_season_name'),
        ),
        migrations.AddConstraint(
            model_name='playerstats',
            constraint=models.UniqueConstraint(fields=('game_id', 'player_id', 'season_id'), name='player_stats_unique_game_player_season'),
        ),
        migrations.AddConstraint(
            model_name='teaminfo',
            constraint=models.UniqueConstraint(fields=('season_id', 'abbreviation'), name='teams_info_unique_season_abbr'),
        ),
        migrations.AddConstraint(
            model_name='teammatchups',
            constraint=models.UniqueConstraint(fields=('season_id', 'team_id', 'game_date'), name='team_matchups_unique_season_team_date'),
        ),
        migrations.AddConstraint(
            model_name='teamroster',
            constraint=models.UniqueConstraint(fields=('team_id', 'player_id', 'season_id'), name='teams_roster_unique_team_player_season'),
        ),
        migrations.AddConstraint(
            model_name='teamstats',
            constraint=models.UniqueConstraint(fields=('game_id', 'team_id', 'season_id'), name='team_stats_unique_game_team_season'),
        ),
    ]
