# Generated by Django 4.2.30 on 2026-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_playerawards_player_awards_unique_player_season_desc_month_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ml_models',
            },
        ),
    ]
