# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_llm_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('season', models.CharField(blank=True, max_length=20, null=True)),
                ('game_id', models.CharField(max_length=20)),
                ('game_date', models.DateField(blank=True, null=True)),
                ('home_team_id', models.IntegerField()),
                ('away_team_id', models.IntegerField()),
                ('game_status', models.IntegerField(blank=True, null=True)),
                ('run_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_schedule',
            },
        ),
        migrations.AddConstraint(
            model_name='gameschedule',
            constraint=models.UniqueConstraint(fields=('game_id',), name='game_schedule_unique_game_id'),
        ),
    ]
