# Generated by Django 4.2.30 on 2026-10-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_team_player_entity_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='MartPlayerGameForm',
            fields=[
                ('season_id', models.CharField(max_length=20)),
                ('season', models.CharField(blank=True, max_length=20, null=True)),
                ('season_type', models.CharField(blank=True, max_length=20, null=True)),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_id', models.IntegerField()),
                ('game_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('game_date', models.DateField(blank=True, null=True)),
                ('game_number', models.IntegerField(blank=True, null=True)),
                ('games_in_season', models.IntegerField(blank=True, null=True)),
                ('is_latest', models.BooleanField(blank=True, null=True)),
                ('pts', models.FloatField(blank=True, null=True)),
                ('reb', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('form_pts', models.FloatField(blank=True, null=True)),
                ('form_reb', models.FloatField(blank=True, null=True)),
                ('form_ast', models.FloatField(blank=True, null=True)),
                ('form_ts_pct', models.FloatField(blank=True, null=True)),
                ('base_pts', models.FloatField(blank=True, null=True)),
                ('base_ts_pct', models.FloatField(blank=True, null=True)),
                ('delta_pts', models.FloatField(blank=True, null=True)),
                ('delta_ts_pct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': '"nba_marts"."mart_player_game_form"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MartTeamGameForm',
            fields=[
                ('season_id', models.CharField(max_length=20)),
                ('season', models.CharField(blank=True, max_length=20, null=True)),
                ('season_type', models.CharField(blank=True, max_length=20, null=True)),
                ('team_id', models.IntegerField()),
                ('game_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('game_date', models.DateField(blank=True, null=True)),
                ('game_number', models.IntegerField(blank=True, null=True)),
                ('games_in_season', models.IntegerField(blank=True, null=True)),
                ('is_latest', models.BooleanField(blank=True, null=True)),
                ('margin', models.FloatField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('form_margin', models.FloatField(blank=True, null=True)),
                ('form_win_pct', models.FloatField(blank=True, null=True)),
                ('form_wins', models.IntegerField(blank=True, null=True)),
                ('form_games', models.IntegerField(blank=True, null=True)),
                ('base_margin', models.FloatField(blank=True, null=True)),
                ('base_win_pct', models.FloatField(blank=True, null=True)),
                ('delta_margin', models.FloatField(blank=True, null=True)),
                ('delta_win_pct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': '"nba_marts"."mart_team_game_form"',
                'managed': False,
            },
        ),
    ]
