from django.db import models


class SeasonRecord(models.Model):
    season_id = models.IntegerField(unique=True)
    season = models.CharField(max_length=20, null=True, blank=True)
    run_timestamp = models.DateTimeField(null=True, blank=True)


class TeamInfo(models.Model):
    season_id = models.IntegerField()
    abbreviation = models.CharField(max_length=10)
    nickname = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    year_founded = models.IntegerField()
    full_name = models.CharField(max_length=100, null=True, blank=True)
    season = models.CharField(max_length=20, null=True, blank=True)
    run_timestamp = models.DateTimeField(null=True, blank=True)


class PlayerInfo(models.Model):
    season_id = models.IntegerField()
    full_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    is_active = models.BooleanField()
    season = models.CharField(max_length=20, null=True, blank=True)
    run_timestamp = models.DateTimeField(null=True, blank=True)


class TeamRoster(models.Model):
    team_id = models.IntegerField()
    player_id = models.IntegerField()
    season_id = models.IntegerField()
    player = models.CharField(max_length=100)
    age = models.IntegerField(null=True, blank=True)
    position = models.CharField(max_length=20, null=True, blank=True)
    season = models.CharField(max_length=20, null=True, blank=True)
    run_timestamp = models.DateTimeField(null=True, blank=True)


class PlayerStats(models.Model):
    season_id = models.IntegerField()
    player_id = models.IntegerField()
    player_name = models.CharField(max_length=100)
    team_id = models.IntegerField()
    team_abbreviation = models.CharField(max_length=10)
    team_name = models.CharField(max_length=50)
    game_id = models.CharField(max_length=20)
    game_date = models.DateField(null=True, blank=True)
    matchup = models.CharField(max_length=50)
    wl = models.CharField(max_length=2, null=True, blank=True)
    min = models.FloatField()
    fgm = models.FloatField()
    fga = models.FloatField()
    fg_pct = models.FloatField()
    fg3m = models.FloatField()
    fg3a = models.FloatField()
    fg3_pct = models.FloatField()
    ftm = models.FloatField()
    fta = models.FloatField()
    ft_pct = models.FloatField()
    oreb = models.FloatField()
    dreb = models.FloatField()
    reb = models.FloatField()
    ast = models.FloatField()
    stl = models.FloatField()
    blk = models.FloatField()
    tov = models.FloatField()
    pf = models.FloatField()
    pts = models.FloatField()
    plus_minus = models.FloatField()
    fantasy_pts = models.FloatField(null=True, blank=True)
    video_available = models.IntegerField(null=True, blank=True)
    season = models.CharField(max_length=20, null=True, blank=True)
    run_timestamp = models.DateTimeField(null=True, blank=True)


class TeamStats(models.Model):
    season_id = models.IntegerField()
    team_id = models.IntegerField()
    team_abbreviation = models.CharField(max_length=10)
    team_name = models.CharField(max_length=50)
    game_id = models.CharField(max_length=20)
    game_date = models.DateField(null=True, blank=True)
    matchup = models.CharField(max_length=50)
    wl = models.CharField(max_length=2, null=True, blank=True)
    min = models.FloatField()
    fgm = models.FloatField()
    fga = models.FloatField()
    fg_pct = models.FloatField()
    fg3m = models.FloatField()
    fg3a = models.FloatField()
    fg3_pct = models.FloatField()
    ftm = models.FloatField()
    fta = models.FloatField()
    ft_pct = models.FloatField()
    oreb = models.FloatField()
    dreb = models.FloatField()
    reb = models.FloatField()
    ast = models.FloatField()
    stl = models.FloatField()
    blk = models.FloatField()
    tov = models.FloatField()
    pf = models.FloatField()
    pts = models.FloatField()
    plus_minus = models.FloatField()
    video_available = models.IntegerField(null=True, blank=True)
    season = models.CharField(max_length=20, null=True, blank=True)
    run_timestamp = models.DateTimeField(null=True, blank=True)


class TeamMatchups(models.Model):
    season_id = models.IntegerField()
    team_id = models.IntegerField()
    team_abbreviation = models.CharField(max_length=10)
    team_name = models.CharField(max_length=50)
    game_id = models.CharField(max_length=20)
    game_date = models.DateField(null=True, blank=True)
    matchup = models.CharField(max_length=50)
    wl = models.CharField(max_length=2, null=True, blank=True)
    min = models.FloatField()
    pts = models.FloatField()
    fgm = models.FloatField()
    fga = models.FloatField()
    fg_pct = models.FloatField()
    fg3m = models.FloatField()
    fg3a = models.FloatField()
    fg3_pct = models.FloatField()
    ftm = models.FloatField()
    fta = models.FloatField()
    ft_pct = models.FloatField()
    oreb = models.FloatField()
    dreb = models.FloatField()
    reb = models.FloatField()
    ast = models.FloatField()
    stl = models.FloatField()
    blk = models.FloatField()
    tov = models.FloatField()
    pf = models.FloatField()
    plus_minus = models.FloatField()
    season = models.CharField(max_length=20, null=True, blank=True)
    run_timestamp = models.DateTimeField(null=True, blank=True)
