from django.db import models

class SeasonRecord(models.Model):
    season_id = models.IntegerField(unique=True)

class TeamInfo(models.Model):
    season_id = models.IntegerField()
    abbreviation = models.CharField(max_length=10)
    nickname = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    year_founded = models.IntegerField()
    full_name = models.CharField(max_length=100, null=True, blank=True)

class PlayerInfo(models.Model):
    season_id = models.IntegerField()
    full_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    is_active = models.BooleanField()

class TeamRoster(models.Model):
    team_id = models.IntegerField()
    player_id = models.IntegerField()
    season_id = models.IntegerField()
    player = models.CharField(max_length=100)
    age = models.IntegerField(null=True, blank=True)
    position = models.CharField(max_length=20, null=True, blank=True)

class PlayerStats(models.Model):
    player_id = models.IntegerField()
    season_id = models.IntegerField()
    team_id = models.IntegerField()
    rank = models.IntegerField()
    player = models.CharField(max_length=100)
    team = models.CharField(max_length=50)
    gp = models.IntegerField()
    min = models.FloatField()
    fgm = models.FloatField()
    fga = models.FloatField()
    fg_pct = models.FloatField()
    fg3m = models.FloatField()
    fg3a = models.FloatField()
    fg3_pct = models.FloatField()
    ftm = models.FloatField()
    fta = models.FloatField()
    ft_pct = models.FloatField()
    oreb = models.FloatField()
    dreb = models.FloatField()
    reb = models.FloatField()
    ast = models.FloatField()
    stl = models.FloatField()
    blk = models.FloatField()
    tov = models.FloatField()
    pf = models.FloatField()
    pts = models.FloatField()
    eff = models.FloatField()
    ast_tov = models.FloatField()
    stl_tov = models.FloatField()
    date = models.CharField(max_length=20)

class TeamStats(models.Model):
    group_value = models.CharField(max_length=50)
    season_id = models.IntegerField()
    team_id = models.IntegerField()
    season_year = models.CharField(max_length=50)
    gp = models.IntegerField()
    w = models.IntegerField()
    l = models.IntegerField()
    w_pct = models.FloatField()
    min = models.FloatField()
    fgm = models.FloatField()
    fga = models.FloatField()
    fg_pct = models.FloatField()
    fg3m = models.FloatField()
    fg3a = models.FloatField()
    fg3_pct = models.FloatField()
    ftm = models.FloatField()
    fta = models.FloatField()
    ft_pct = models.FloatField()
    oreb = models.FloatField()
    dreb = models.FloatField()
    reb = models.FloatField()
    ast = models.FloatField()
    tov = models.FloatField()
    stl = models.FloatField()
    blk = models.FloatField()
    blka = models.FloatField()
    pf = models.FloatField()
    pfd = models.FloatField()
    pts = models.FloatField()
    plus_minus = models.FloatField()
    gp_rank = models.IntegerField()
    w_rank = models.IntegerField()
    l_rank = models.IntegerField()
    w_pct_rank = models.IntegerField()
    min_rank = models.IntegerField()
    fgm_rank = models.IntegerField()
    fga_rank = models.IntegerField()
    fg_pct_rank = models.IntegerField()
    fg3m_rank = models.IntegerField()
    fg3a_rank = models.IntegerField()
    fg3_pct_rank = models.IntegerField()
    ftm_rank = models.IntegerField()
    fta_rank = models.IntegerField()
    ft_pct_rank = models.IntegerField()
    oreb_rank = models.IntegerField()
    dreb_rank = models.IntegerField()
    reb_rank = models.IntegerField()
    ast_rank = models.IntegerField()
    tov_rank = models.IntegerField()
    stl_rank = models.IntegerField()
    blk_rank = models.IntegerField()
    blka_rank = models.IntegerField()
    pf_rank = models.IntegerField()
    pfd_rank = models.IntegerField()
    pts_rank = models.IntegerField()
    plus_minus_rank = models.IntegerField()
    date = models.CharField(max_length=20)